language: python

python: 2.7

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache: pip

before_install: pip install flake8

script: flake8 -v .
